name: flutter_test_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  http: ^1.1.0
  font_awesome_flutter: ^10.2.1
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  dio: ^5.9.0           # 改为兼容版本
  dio_http2_adapter: ^2.1.1  # 新增 Dio HTTP/2 适配器
  adaptive_theme: ^3.7.1+2
  fl_chart: ^1.0.0
  flutter_svg: ^2.2.0
  provider: ^6.1.5+1
  web_socket_channel: ^3.0.3
  shared_preferences: ^2.5.3
  archive: ^4.0.7

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/行情页广告图.png
    - assets/images/行情页指数图.png
    - assets/images/news_red.png
    - assets/images/news_blue.png
    - assets/images/ad_banner.png
    - assets/images/book.svg

    - assets/images/logo.png
    - assets/svgs/theme.svg
    - assets/svgs/earth.svg
    - assets/svgs/change.svg
    - assets/svgs/email.svg
    - assets/svgs/lock.svg
    - assets/svgs/done.svg
    - assets/svgs/red_green.svg
    - assets/svgs/green_red.svg
    - assets/svgs/setting_theme.svg
    - assets/svgs/coin_detail.svg
    - assets/images/hot.png
    - assets/images/week.png
    - assets/images/topic.png
    - assets/images/fake.png
    - assets/images/dark.png
    - assets/images/light.png
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/PostNoBillsColombo-ExtraBold.ttf
          weight: 800
