name: flutter_test_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  http: ^1.1.0
  font_awesome_flutter: ^10.2.1
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  dio: ^5.9.0           # 改为兼容版本
  dio_http2_adapter: ^2.1.1  # 新增 Dio HTTP/2 适配器
  adaptive_theme: ^3.7.1+2
  fl_chart: ^1.0.0
  flutter_svg: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/home_page/container/
    - lib/splash_screen_page/
    - assets/images/行情页广告图.png
    - assets/images/行情页指数图.png
    - assets/images/news_red.png
    - assets/images/news_blue.png
    - assets/images/ad_banner.png
    - assets/images/book.svg
    - assets/images/hot.svg
    - assets/images/week.svg
    - assets/images/topic.svg
    - assets/images/fake.svg
    - assets/images/logo.png
